### ISSUE TITLE
Top Banner

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/everythinghome.homeowner.ai#3]
How can i make the font larger and add an arrow? 
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/66ccd679-3c74-471e-8026-b63d44b028c8)

**Comment by codextiny** [comment]
@shannonbaldwin 
You can edit top banner setting from here, please below screenshot.

![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/113863175/27410328-c8c7-4eb2-bd15-60fcf6ae15a2)

When you click on top banner, it will go to the setting where you can edit styles and sizes but can't add icons because there is no option to add icon but we can add image if you will provide us. see screenshot below:

![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/113863175/f5fcc4ae-0986-46a4-a89a-ce60b1b5d6b6)

**Comment by shannonbaldwin** [comment]
@codextiny Please add the the logo icon and an arrow to the top banner. The "find out how" should be highlighted in the teal color when hovered over.

[LabCoat Agents logo] LabCoat agents, get your own branded version of EverythingHome for your team or brokerage. [Find out how(url)] [Arrow Icon in white]


![lca logo icon](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/f9496a0d-4f29-4728-948c-19ef614b09a8)

![white arrow EH](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/cca4b577-6193-4301-a7f3-8151a7b1e556)

**Comment by shannonbaldwin** [comment]
@codextiny Please make sure the logo icon is smaller. Also, the two sentences need to be aligned as well as the arrow.
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/c196f5c0-69fc-4cf2-bb3e-4364d164ef97)
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/c196f5c0-69fc-4cf2-bb3e-4364d164ef97)
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/c196f5c0-69fc-4cf2-bb3e-4364d164ef97)

**Comment by codextiny** [comment]
@shannonbaldwin, 

yes, we have fixed it, we were working on it that's why it looks weird .
Please check now and let us know if you have any issue .

Thanks,
Codextiny

**Comment by shannonbaldwin** [comment]
@codextiny Looks good!
