### ISSUE TITLE
Resources Page

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/everythinghome.homeowner.ai#6]
I want the Marquee on our Resources page on everythinghome.homeowner.ai/agents to have this similar setup to the below link. I added the marquee bar but need to figure out how to link those to the blog sections.
[
](https://trustengine.com/downloads/)

**Comment by shannonbaldwin** [comment]
I've updated the Resource page and added a nav bar. I will not have a description underneath so need to remove that space. I also would like the tabs underlined, versus boxed in.

**Comment by codextiny** [comment]
@shannonbaldwin 

Please provide some screenshots and url's for better understanding .?

**Comment by shannonbaldwin** [comment]
@codextiny This is the nav bar I added to the Resources page. I do not want the colored border. I would rather have them underlined as you click through like the example below. 


![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/1b92e3a5-baa0-4bdd-9552-40a15378ca6b)

![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/53e7d9ef-a8f9-4d9b-9900-e32d41d9ddd6)

I also want each tab to bring up the corresponding blog posts (I created the posts already in WP).

**Comment by codextiny** [comment]
@shannonbaldwin 

can you please share the link as well ??

**Comment by shannonbaldwin** [comment]
@codextiny[ ](https://trustengine.com/downloads/)

**Comment by shannonbaldwin** [comment]
@codextiny https://trustengine.com/downloads/

**Comment by codextiny** [comment]
@shannonbaldwin 


Please confirm, We are assuming that you want show your posts (see screenshot below) with filters on this page: everythinghome.homeowner.ai/agents.

![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/113863175/ee66570b-ca7e-4e6e-9aa2-aa77ad1e2a3d)


As you can see this widget does not have any ability to show posts it can show media and text only. 

![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/113863175/aab697d7-270f-4485-b059-052970418829)


We have also reviewed your Elmentor theme it has a built-in widget to show posts but it does not have filters functionality. You can edit all posts and button through elementor except few things like button active state etc.
Post Widget: 

![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/113863175/5a1df1ab-f617-4290-afdc-485847d886f1)

 

The solution we have here is, we have to create custom buttons container and link them to posts widget through unique category classes. In posts there is an option to select category and we will apply filters according to categories. You can see the categories column in the screenshot below.
 
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/113863175/d6d5df45-3142-4ec8-ad07-f8486b0a3825)

Please check all the functionality and let us know if we missed something here so we could act accordingly, because it will take time.

Thanks,
Team Codextiny

**Comment by shannonbaldwin** [comment]
@codextiny I want to be able to have a section of posts like this example but have the nav bar or something similar to toggle between each post section.![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/4139d8d2-b9a7-4328-84ca-0bb7685a17a5)

This example is from a template in WP. See here.[ ](https://everythinghome.homeowner.ai/support-and-training/?preview_id=2091&preview_nonce=e063127fef&preview=true)

**Comment by codextiny** [comment]
Can you please give me the page URL and them widget name? so i can have a look

**Comment by shannonbaldwin** [comment]
@codextiny I cannot remember where I pulled that section and/or widget! Here it is in the other website that I saved.
https://everythinghome.homeowner.ai/support-and-training

**Comment by codextiny** [comment]
@shannonbaldwin 

We found the the widget, basically its a carousel and applying filters upon carousels does not work properly and i may effect the sliding animations etc.

**Comment by shannonbaldwin** [comment]
@codextiny If I go your custom route, will I be able to show videos and/or images on the posts? Your example above only shows words. I just want to make sure it can have same look as my example of the carousel.

**Comment by codextiny** [comment]
@shannonbaldwin 

That widget has feature to show the featured images of posts
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/113863175/d62c7ac7-945f-47b1-a8dc-4f774095f6c2)

See this screenshot this image will be showing there.
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/113863175/c91e51ec-bc3d-47dd-a041-3313f091616e)

but I am not able to found the video option here.

Please check this link ( https://everythinghome.homeowner.ai/wp-admin/post.php?post=2091&action=elementor ) I have added the posts widget but didn't published the page you can remove that widget after having a look at the functionality.

**Comment by shannonbaldwin** [comment]
@codextiny Will I have a navigation option like this screenshot from earlier with the custom route?![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/99db9a51-9530-4da7-8925-df17419f23dd)

**Comment by codextiny** [comment]
Hi @shannonbaldwin 
We assume you are talking about this screenshot
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/113863175/fb7e5966-0177-420b-8e7f-6f1e029e6780)
If yes we mentioned this before ( **it's a carousel and applying filters upon carousels does not work properly and it may affect the sliding animations etc after filtering.** )
We always mention this to our clients before starting because the carousel/sliders do not work properly after applying the filter's functionality.

**Comment by shannonbaldwin** [comment]
@codextiny No, I am asking about being able to filter off of a menu just like this screenshot below that we discussed in the beginning.![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/72a2fdfe-6087-4e88-8458-601c30c92525)

**Comment by codextiny** [comment]
@shannonbaldwin 

Yes we can create a filters widget similar to this one
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/113863175/82f06f4d-7499-4103-a5e1-208d6584d295)

and attach it with JS functionality to this section
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/113863175/35e9d88b-7b59-4edf-b22c-0a688c9f669a)

**Comment by shannonbaldwin** [comment]
@codextiny Let's please use your custom posts here and add the filters widget with the underline feature like the screenshot. Can you confirm that these posts are filtered by category? I would like to start adding content asap so please let me know when complete.

**Comment by codextiny** [comment]
Yes the posts will be filtered by category 
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/113863175/26ef4ac7-6b21-4279-8f24-c734de9542a5)

you can place this widget and start updating the content we can add the filters later
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/113863175/7339f157-7c89-4e33-8a70-2afa428463cc)

**Comment by shannonbaldwin** [comment]
@codextiny We have setup a portfolio for this page on[ ](https://everythinghome.ai/agents/resources/). 

Can you please:
1. Adjust the nav tab to be left aligned
2. Install underline feature for each category title we discussed above
3. Ensure that each category navigates to the corresponding posts

<img width="1291" alt="image" src="https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/adefa7b6-66d0-4765-8116-55e43fc1c3bb">

**Comment by shannonbaldwin** [comment]
@codextiny Also, please make videos as light box. 
<img width="1381" alt="image" src="https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/e17a2eca-3ce3-4e67-8006-c7790cdf6c19">

**Comment by codextiny** [comment]
@shannonbaldwin 

we have updated the navbar alignment and added the underline feature for each category and fixed the posts so now each category navigates to the corresponding posts

Please have a look and let us know if you have any questions.

**Comment by shannonbaldwin** [comment]
@codextiny When you click on each category, it takes you to the top of the web page, versus the different sections. ![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/4c3b68a9-afa8-4fa6-b80c-e99ca37327d4)

**Comment by shannonbaldwin** [comment]
@codextiny Please remove "ALL" from the categories and make the titles bold and in black font. Please have "Get Started" as default category that is underlined. ![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/51ff8492-41e8-48a9-b821-b93c5bea39b7)

**Comment by codextiny** [comment]
@shannonbaldwin 

There is no option in this widget to select a category by default and remove all button but we have made it hidden with codes forcefully.

We have also made the categories bold and added the functionality to auto scroll on category page.

Important note: If you will ever remove this widget from this page than we need to add all the functionality again.

**Comment by shannonbaldwin** [comment]
@codextiny Per my question above, can you make the first tab underlined by default?
![image](https://github.com/shannonbaldwin/everythinghome.homeowner.ai/assets/167017886/6c120457-cc99-4a0f-acbe-33f1625f696e)
